### ISSUE TITLE
Don't send analytics data without permission

### ISSUE THREAD

**Issue by nmushegian** [cgewecke/hardhat-gas-reporter#102]
The gas reporter is hitting the coinmarketcap API without asking or telling

<img width="563" alt="Screen Shot 2022-03-04 at 5 44 41 PM" src="https://user-images.githubusercontent.com/924397/156849053-cb74b7eb-2d47-4b0d-bca7-d49053ab2743.png">

**Comment by cgewecke** [comment]
This isn't sending analytics data. It's requesting price data.

**Comment by nmushegian** [comment]
There is a lot of metadata in the request
Coinmarketcap is not exactly a “no logs” company
I’m not suggesting you are collecting analytics data, but someone is

**Comment by cgewecke** [comment]
@nmushegian What would make you most comfortable here? No requests by default?

**Comment by nmushegian** [comment]
I think that's reasonable. FWIW in my experience the only other entities that ships packages that make spurious requests, is are Facebook and Google.

One possible usage
- print a helpful one liner like `no price provider configured, type <relevant help command> for info` at start of report
- `not configured` or similar as default value in the table
- you can provide the url as an env var or part of the hardhat config

One side benefit of encouraging an explicit `PRICE_RPC_URL` is eventually we can swap it out with some nice eth AMM backed whatever. Like how we can swap `ETH_RPC_API` now that theoretical concerns about Infura are becoming real.

**Comment by cgewecke** [comment]
Fixed in eth-gas-reporter 0.2.26 

rip @nmushegian
