### ISSUE TITLE
Don't open ports for no reason

### ISSUE THREAD

**Issue by nmushegian** [cgewecke/hardhat-gas-reporter#103]
Preventing this connection makes no apparent difference to the output of the reporter (if it does then I missed it). If it has some reason to accept incoming connections, it should only do so when it has an apparent cause and effect (ie, I flip a config setting that shows me some new useful info as a result of this network connection)

<img width="348" alt="Screen Shot 2022-03-04 at 5 48 32 PM" src="https://user-images.githubusercontent.com/924397/156849438-87bf5da4-2a90-4981-99a2-173211a8eebd.png">

**Comment by cgewecke** [comment]
RIP nikolai 

(I think this was fixed on 1.0.9)
