### ISSUE TITLE
Yarn test-gas 

### ISSUE THREAD

**Issue by ClubPEC** [cgewecke/hardhat-gas-reporter#105]
Hi All

Just Launched my ERC721 for my projetc PenguinExchangeClub.uk  ,want to check gas report . Using Hardhat
below error pops up eavery time i run the test.

yarn run v1.22.15
warning package.json: No license field
$ REPORT_GAS=1 hardhat test
'REPORT_GAS' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.

Any perticular reason ?

Thanks 
PEC

**Comment by cgewecke** [comment]
@ClubPEC What operating system or shell are you using?
