### ISSUE TITLE
High gas view funcs not being reported

### ISSUE THREAD

**Issue by 0xBeans** [cgewecke/hardhat-gas-reporter#113]
I have a view function (tokenURI) that processes onchain SVGs and uses ~15M in gas (according to foundry). 

However, when running a similar test in HH and using gas reporter, tokenURI is left out from the gas reporter table (all other funcs are present). I assume it is due to the high gas usage of this function?

**Comment by cgewecke** [comment]
@0xBeans The gas reporter records gas usage by looking at transaction receipts and doesn't measure view or pure methods as such.  You could get an approximation by executing the view in a state-changing wrapper like:

```solidity
function executeTokenURI() external {
  tokenURI();
} 
```

(Issue #92 tracks adding support for view and pure methods as an option.)

**Comment by 0xBeans** [comment]
Ah I see, I wasnt aware of that. Appreciate the info!
