### ISSUE TITLE
Feature Request: Add price in ETH

### ISSUE THREAD

**Issue by dievardump** [cgewecke/hardhat-gas-reporter#117]
Hey there!

I have a feature request: 

I would love to be able to see the cost in ETH according to the gasPrice set in the configuration. 

As a developer/deployer, I really don't care about price in currencies, I'm deploying with ETH and would like to be able to know approximately how much ETH it will cost me. It is also a lot easier to see cost variations after changes.

**Comment by vladikopl01** [comment]
You could just change the currency in hardhat-gas-reporter config in `hardhat.config.ts` file to "ETH", as follows:
`gasReporter: {
    coinmarketcap: envConfig.coinmarketcapApiKey,
    currency: 'ETH',
    showTimeSpent: true,
    enabled: envConfig.showLogs,
  },`

**Comment by Jerrywang959** [comment]
> 您可以在 hardhat-gas-reporter 配置中更改货币 `hardhat.config.ts`文件到“ETH”，如下：
> 
> ```
> gasReporter: {
>     coinmarketcap: envConfig.coinmarketcapApiKey,
>     currency: 'ETH',
>     showTimeSpent: true,
>     enabled: envConfig.showLogs,
>   },
> ```

Do I still need to set `coinmarketcap`? I tried to set currency as ETH but it didn't work. I use hardhard-deploy plugin without ethers in deploy scripts. The gas reporter can only show gas used.

My config:

```
  gasReporter: {
    enabled: process.env.REPORT_GAS !== undefined,
    currency: 'ETH',
    gasPrice: 5,
    showTimeSpent: true,
  },
```

My report:
![image](https://user-images.githubusercontent.com/59097122/190973968-0f9ccfd7-7146-463b-b8fc-b87ef1bf48ec.png)

**Comment by dievardump** [comment]
> You could just change the currency in hardhat-gas-reporter config in `hardhat.config.ts` file to "ETH", as follows:

Thank you! 

The feature request was mainly so I do not have to use coinmarketCapApi to know how much eth it needs since it's 1:1

**Comment by cgewecke** [comment]
In the latest version you can also set token price to acheive this:

```
tokenPrice: "1"
```

https://github.com/cgewecke/hardhat-gas-reporter/releases/tag/v2.0.0
