### ISSUE TITLE
Gas report not shown per unit tests

### ISSUE THREAD

**Issue by ghost** [cgewecke/hardhat-gas-reporter#119]
Hello,

My `npx hardhat test` command doesn't generate gas report per unit tests,

But instead, it will only show the gas report at the end of the test.

How to enable this?

Thanks.

My hardhat config btw

```js
gasReporter: {
    enabled: true,
    currency: 'USD',
    showMethodSig: true,
  },
```

**Comment by vladikopl01** [comment]
Same problem, only can get time spent on specific function by adding `showTimeSpent: true`

**Comment by CJ42** [comment]
Same problem, with a sample Hardhat setup, and I do not get the gas cost per unit test.

![image](https://user-images.githubusercontent.com/31145285/181293538-ebe7eef2-b855-4e38-b238-1c0559aad4e4.png)

However, with truffle, I do get the gas cost per unit test:

![image](https://user-images.githubusercontent.com/31145285/181293665-f222ef8e-488d-4ff5-9b76-deb5cb165d47.png)

**Comment by vetal20600** [comment]
got same problem

hardhat: 2.9.9
hardhat-gas-reporter: 1.0.8

**Comment by vetal20600** [comment]
> Same problem, only can get time spent on specific function by adding `showTimeSpent: true`

true

**Comment by vetal20600** [comment]
interesting that gas outputs when testing against ropsten

**Comment by nxqbao** [comment]
Got same problem here

**Comment by aolin118** [comment]
same problem here

**Comment by jacobmakarsky** [comment]
ever figure this out?

**Comment by cgewecke** [comment]
Apologies, this behavior was only available in eth-gas-reporter and it slows the plugin down enormously because it has to use sync network calls to work with the mocha reporter.

Am going to add additional tasks in v2.0 that let you add gas tracking to any hardhat script and look at different scenario costs.

Closing for now....
