### ISSUE TITLE
Gas reporter hides Mocha test durations

### ISSUE THREAD

**Issue by erhant** [cgewecke/hardhat-gas-reporter#123]
Mocha normally displays a duration for each test, when it exceeds the `slow` parameter. See <https://mochajs.org/#test-duration> Enabling gas reporter **hides** this test duration report, even if you set `slow` to be `0`. 

You can test with the following hardhat configuration:

```js
gasReporter: {
    enabled: true // set false to see durations by mocha
  },
  mocha: {
    slow: 0 // (ms) set slow to 0 to display all durations, default 75ms
  },
```

As a workaround for now, I just wrote `console.time(someLabel)` under `beforeEach` and `console.timeEnd(someLabel)` under `afterEach`.

**Comment by cgewecke** [comment]
There is an option for this documented in the README. It's called`showTimeSpent`.
