### ISSUE TITLE
Adding hardhat-gas-reporter breaks chai expect(BigInt) check

### ISSUE THREAD

**Issue by valar999** [cgewecke/hardhat-gas-reporter#129]
```js
const { ethers } = require("hardhat");
const { expect } = require("chai");

describe("Test", function () {
  it("should exit with error", async function () {
    expect(1n).to.equal(2n);
  });
});
```

It ends immediately without reporting and even exit code is 0.

Everything works as expected if you remove `hardhat-gas-reporter` from `hardhat.config.js` or replace expect that use BigNum with `expect(1).to.equal(2);`

Example: https://github.com/valar999/bug-hardhat-gas-reporter

**Comment by cgewecke** [comment]
In the latest version we use chai expect and BigInt in the integration tests here and everything works as expected. Closing because this issue is quite old and believe this has been resolved. Just ping if anyone runs into this again.
