### ISSUE TITLE
Output to both stdout and file

### ISSUE THREAD

**Issue by sebastiantf** [cgewecke/hardhat-gas-reporter#130]
Would be really nice to have an option to print output both to stdout and file, instead of having to choose either one at a time

**Comment by cgewecke** [comment]
This is supported in the latest release (2.0). The following options combination outputs the report to file (without color) and to terminal (with color)
```ts
outputFile: "./myfile...",
forceTerminalOutput: true,
forceTerminalOutputFormat: "terminal"
```


https://github.com/cgewecke/hardhat-gas-reporter/releases/tag/v2.0.0
