### ISSUE TITLE
Gas usage changes by simply moving the contract file

### ISSUE THREAD

**Issue by sebastiantf** [cgewecke/hardhat-gas-reporter#134]
I notice something weird. I moved a contract source code from the path `./contracts/tokens/ERC721Token.sol` to `./contracts/tokens/erc721/ERC721Token.sol` (basically moved the contract into a subdirectory) and the gas usage reported for that contract deployment changed from `644383` to `644371`, a change of 12 gas units.

Why does that happen?

**Comment by cgewecke** [comment]
I have seen flicker like this in the past and tried to track it down. But the gas reporter literally just reads the receipt. 

There might be some kind of gas bug or strangeness deeper in the stack, at ethereumjs-vm possibly. It's not huge... just a few gas. 

Am closing for now - have looked into this before without discovering anything unfortunately.
