### ISSUE TITLE
token option has no effect

### ISSUE THREAD

**Issue by Obyka** [cgewecke/hardhat-gas-reporter#140]
I'm trying to use hardhat-gas-reporter with Polygon.
To do so, I have :
- created a coinmarket account and exported the private key in `.env` file
- modified `hardhat.config.js` to use MATIC and my country's currency

When I generate the report, the token and gas prices are still based on Ethereum instead of Polygon
Here is my config and my output:
```
  gasReporter: {
    currency: "CHF",
    token: "MATIC",
    coinmarketcap: process.env.COINMARKETCAP || null,
    enabled: true,
  },
```

![image](https://user-images.githubusercontent.com/28777250/211579962-4d590da1-cb3f-4421-a8a5-6729716b3a46.png)

Calls are being made to the coinmarket API, but with ETH as symbol.
![image](https://user-images.githubusercontent.com/28777250/211580190-fd3e3d8a-c520-4629-a602-15f6f65946cc.png)

What I expected: An output with MATIC price and symbol

**Comment by cgewecke** [comment]
I'm not sure why this wasn't working for you, nothing jumps out as wrong in your config. I just now used:

```
gasReporter: {
    coinmarketcap: process.env.CMC_API_KEY,
    token: "MATIC",
    gasPriceApi: "https://api.polygonscan.com/api?module=proxy&action=eth_gasPrice"
  }
```

and got:

![Screen Shot 2024-01-30 at 7 34 30 PM](https://github.com/cgewecke/hardhat-gas-reporter/assets/7332026/772a7a08-f51d-4b44-8ccf-247d4acc7076)

which is pretty close to polygonscan rn:

![Screen Shot 2024-01-30 at 7 35 04 PM](https://github.com/cgewecke/hardhat-gas-reporter/assets/7332026/d3ec8b4b-f457-4071-b2cc-6abf2d2af5f1)

Closing
