### ISSUE TITLE
Only child contract's name shows in report

### ISSUE THREAD

**Issue by sebastiantf** [cgewecke/hardhat-gas-reporter#141]
I have an upgradeable contract `UnlockFactory` and another contract `TestUnlockFactoryV2` that is only used for tests and inherits the former. Even though I'm using `UnlockFactory` for most of the tests, the report only includes `TestUnlockFactoryV2`. When I exclude `TestUnlockFactoryV2`, the name then changes to `UnlockFactory` in the report:

<img width="1080" alt="Screenshot 2023-01-19 at 12 30 40 PM" src="https://user-images.githubusercontent.com/36922376/213376537-ed8db981-05c0-417b-9255-9fae6c97fe73.png">

I was using v1.0.8 and tried upgrading to v1.0.9, but the issue still persists
I think this might be related to #121

**Comment by cgewecke** [comment]
I think this was the same problem as #154 and OZ Upgrades related. Closing but just ping if that's not the case.
