### ISSUE TITLE
Gas report file corrupted

### ISSUE THREAD

**Issue by gokulstevee** [cgewecke/hardhat-gas-reporter#142]
When I generate gas report file using hardhat-gas-reporter package...I get the resulted file as I shown below
I'm using ubuntu 20.04 LTS on WSL2

![gasReporter - StakingToken  WSL_ Ubuntu  - Visual Studio Code 22-01-2023 15_39_47](https://user-images.githubusercontent.com/65470058/213910546-c0895282-19ab-4d25-a195-7ecba4eb14e4.png)

**Comment by lescaudr** [comment]
Make sure to set the noColors to true:

```
    gasReporter: {
        enabled: true,
        currency: "EUR",
        outputFile: "gas-report.txt",
        noColors: true,
        coinmarketcap: process.env.COINMARKETCAP_API_KEY,
        token: "ETH",
    },
```
