### ISSUE TITLE
how to estimate gas for Optimisim and Arbitrum Nova?

### ISSUE THREAD

**Issue by Andriy-Kulak** [cgewecke/hardhat-gas-reporter#148]
Hi Team! 

Is there a way to generate gas costs for Opitimism & Arbitrum? There is no documentation on which tokens are supported. i tried adding token "OP" for optimism which seems to work but costs seem really low so I am not sure if I should trust them since there is no documentation on which tokens can be passed in.

If OP / Arbitrum is not supported here, is there a way to estimate gas costs of contract deployment and method execution using hardhat?

**Comment by math77** [comment]
I'm interested too

**Comment by cgewecke** [comment]
Support for optimism has been added in the latest release (2.0). To get gas usage for that network just set the `L2` option as below:
```ts
gasReporter: {
  L2: "optimism"    
}
```

Arbitrum support is in the pipeline and being tracked via #181. Closing here as partially complete in favor of #181.


https://github.com/cgewecke/hardhat-gas-reporter/releases/tag/v2.0.0
