### ISSUE TITLE
Wrong gwei/gas value causes wrong tx price calculation

### ISSUE THREAD

**Issue by AndriianChestnykh** [cgewecke/hardhat-gas-reporter#149]
It looks like that the Gas Reporter might take the same gwei/gas price for all the networks instead of using a specific network values.

It looks correct for the ETH mainnet:

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/17526648/221811725-d163bcab-e36e-4fb0-a741-7455a79612b3.png">

But it the same for the Polygon, which is approx. 10 times lower than the real value:

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/17526648/221812191-43d54dfa-4037-4709-b419-b2ce13249545.png">

**Comment by cgewecke** [comment]
It's necessary to configure the `gasPriceAPI` option to get network appropriate gas prices. It's documented in the README.
