### ISSUE TITLE
hardhat-gas-reporter doesnt work on npx hardhat test 

### ISSUE THREAD

**Issue by web3dopamine** [cgewecke/hardhat-gas-reporter#150]
I tried running `hardhat-gas-reporter` in hardhat default template it doesn't work with `npx hardhat test`, we have to use flag `REPORT_GAS=true` then only it will run contract which has test script written.

![image](https://user-images.githubusercontent.com/14943387/222537698-67629b02-5f4a-40b1-a525-abd54fc77efd.png)
![image](https://user-images.githubusercontent.com/14943387/222537890-5957e409-0b93-4bac-a9db-f8eb259531d5.png)

NFT.sol contract report is not generated (at all) in none of the cases.

![image](https://user-images.githubusercontent.com/14943387/222538042-18f6b011-9979-424d-bb25-472deb0ff37a.png)

tried on node version 16 & 17

**Comment by Madeindreams** [comment]
In my case, even when using the flag, it does not report anything at all. All is see is the header of the table.

using hardhat  2.18.2
hardhat-gas-reporter 1.0.9
node 16.17.1


![image](https://github.com/cgewecke/hardhat-gas-reporter/assets/17243647/e11fadf2-a288-4b04-8416-3810ff7c1ac1)

**Comment by HarukiKondo** [comment]
·----------------------------------------|---------------------------|-------------|-----------------------------·
|          Solc version: 0.8.20          ·  Optimizer enabled: true  ·  Runs: 200  ·  Block limit: 30000000 gas  │
·········································|···························|·············|······························
|  Methods                                                                                                       │
···················|·····················|·············|·············|·············|···············|··············
|  Contract        ·  Method             ·  Min        ·  Max        ·  Avg        ·  # calls      ·  jpy (avg)  │
···················|·····················|·············|·············|·············|···············|··············
|  MockERC1155NFT  ·  burn               ·          -  ·          -  ·      26033  ·            1  ·          -  │
···················|·····················|·············|·············|·············|···············|··············
|  MockERC1155NFT  ·  burnBatch          ·      32316  ·      32336  ·      32326  ·            3  ·          -  │
···················|·····················|·············|·············|·············|···············|··············
|  MockERC1155NFT  ·  mint               ·          -  ·          -  ·      53347  ·            7  ·          -  │
···················|·····················|·············|·············|·············|···············|··············
|  MockERC1155NFT  ·  mintBatch          ·      79847  ·      79871  ·      79859  ·            9  ·          -  │
···················|·····················|·············|·············|·············|···············|··············
|  MockERC1155NFT  ·  safeTransferFrom   ·      57103  ·      57115  ·      57107  ·            3  ·          -  │

**Comment by HarukiKondo** [comment]
Hey ! I have same error

**Comment by HarukiKondo** [comment]
my project's library versions
"ethers": "6.1.0",
    "hardhat": "2.18.3",
    "hardhat-gas-reporter": "^1.0.9",

**Comment by HarukiKondo** [comment]
↑ It solved!!
