### ISSUE TITLE
The command 'npx hardhat test' hangs and does not proceed when I enable the gas-reporter.

### ISSUE THREAD

**Issue by 1329576606** [cgewecke/hardhat-gas-reporter#155]
The command 'npx hardhat test' hangs and does not proceed when I enable the gas-reporter.

system:Ubuntu 22.04.3 LTS
"hardhat": "2.13.0"
"hardhat-gas-reporter": "1.0.9"

**Comment by cgewecke** [comment]
Without reproduction steps this isn't possible to address. Closing.
