### ISSUE TITLE
Missing viem support

### ISSUE THREAD

**Issue by muhammetaliakbay** [cgewecke/hardhat-gas-reporter#157]
- The `EGRDataCollectionProvider` doesn't record `eth_sendTransaction` requests which `viem` uses.
- Injecting the modified provider in `TASK_TEST_RUN_MOCHA_TESTS` sub task is too late as `viem` reads and freezes the provider instance on the module load.

These two problems are causing the gas reporter miss some TX calls made via `viem`.

**Comment by muhammetaliakbay** [comment]
A PR introducing a patch for adding `viem` support is ready to be reviewed.

**Comment by cgewecke** [comment]
@muhammetaliakbay Has written a nice patch for this problem which is published at the **viem** tag. You can install it with
```
npm install --save-dev hardhat-gas-reporter@viem
```

⚠️ **Important**: for the plugin to work correctly, it must be listed **before** the `hardhat-viem` plugin in `hardhat.config.ts`

There is ongoing work to make this part of the normally published plugin in #167 but it will not be released until v2.0 (probably end of February at the earliest).

**Comment by cgewecke** [comment]
This is fixed in the latest version (2.0). Thanks again for your work on this.
