### ISSUE TITLE
Donating Funds to Hardhat-Gas-Reporter Repo

### ISSUE THREAD

**Issue by Lfada** [cgewecke/hardhat-gas-reporter#159]
Hi Hardhat-Gas-Reporter maintainers. I'm Lucas, a core contributor to the Drips project (https://www.drips.network/). I help recipients of donations through their learning and onboarding process.

[OpenZeppelin](https://www.openzeppelin.com/) has been using https://github.com/cgewecke/hardhat-gas-reporter. It's one of their most critical dependencies!

OpenZeppelin core contributors appreciate your work and want to ensure you are all well-funded to keep doing it. For that reason, they have decided to donate some funds to your project through [Drips](https://www.drips.network/)

Who can I talk to about it?

cc: @cgewecke @alcuadrado @stevyhacker

**Comment by cgewecke** [comment]
@Lfada Thanks! That's very kind of them. I'm the principle maintainer here. You can email me at christophergewecke@gmail.com

**Comment by cgewecke** [comment]
@Lfada I was able to claim everything through your wonderful dAPP - thanks so much for this. Thank you Zeppelin as well.
