### ISSUE TITLE
Support hardhat

### ISSUE THREAD

**Issue by cgewecke** [cgewecke/hardhat-gas-reporter#34]
A list of known issues:

- New provider design (see [buidler 608][1]) 
- New artifact pipeline (see [synthetix 739][2])

**Update: a beta is available**
```
npm install --save-dev hardhat-gas-reporter@beta
```
(It may be missing some data if your project contains shadowed contract names. See more [below][4])

[1]: https://github.com/nomiclabs/buidler/pull/608
[2]: https://github.com/Synthetixio/synthetix/pull/739
[4]: https://github.com/cgewecke/buidler-gas-reporter/issues/34#issuecomment-718293330

**Comment by alcuadrado** [comment]
Hey Chris!

Lot's of new things are coming out with hardhat. We'll have a migration guide for plugins in a few days.

We also took some time to adapt solidity-coverage. We'll send a PR soon. We are just finishing some details on how plugins are managed. Hardhat will be closer to the og version of Buidler, were plugins were just imported/required. This means that users won't need to deal with the type extensions manually.

**Comment by alcuadrado** [comment]
Hey @cgewecke, we have a migration guide for plugins now: https://github.com/nomiclabs/buidler-ts-plugin-boilerplate/blob/hardhat-migration/MIGRATION.md

There are `@rc` version of the hardhat plugins now. The main package is `hardhat`, and the plugins `@nomiclabs/hardhat-*`

**Comment by cgewecke** [comment]
@alcuadrado 

Do you think it might make sense to make a new repo called `hardhat-gas-reporter` and deprecate this one?

**Comment by alcuadrado** [comment]
We are planning to rename the repos and leave a 1-line message explaning about the migration in the readme.

**Comment by mudgen** [comment]
@cgewecke @alcuadrado 
How is adding support for hardhat coming along?

**Comment by cgewecke** [comment]
@mudgen Will look at this weekend. Should be simple here...

**Comment by jmonteer** [comment]
hola! 

any news on the support for hardhat?

thanks!

**Comment by cgewecke** [comment]
@jmonteer Doing it today!! Swear.

**Comment by mudgen** [comment]
@cgewecke You are the man!

**Comment by mudgen** [comment]
@cgewecke  How is it going?   I am curious.  Is it easy or hard to port a buidler plugin to hardhat?

**Comment by alcuadrado** [comment]
Let me know if you need help with this, Chris!

**Comment by cgewecke** [comment]
@alcuadrado Thanks Patricio!

**Comment by cgewecke** [comment]
@mudgen There's a beta published now if you need this ASAP. 
```
npm install --save-dev hardhat-gas-reporter@beta
```

If there are contracts that Hardhat needs a [path-qualified name][1] to load the artifact of, they'll be missing from the report. 

This should only happen if the contract name is duplicated somewhere in the project (like in a node_modules dependency) or you're staging multiple versions of the same contracts in your project (like `old/`, `new/`)

[1]: https://hardhat.org/guides/migrate-from-buidler.html#importing-artifacts-and-ambiguous-names

**Comment by mudgen** [comment]
@cgewecke Great. Thank you.

**Comment by cgewecke** [comment]
This is out as hardhat-gas-reporter@1.0.0

Please just lmk if you run into problems with this. One thing that jumped out in e2e testing is that projects with qualified contract names have wide reports. (Perhaps over-wide, really) 

Addressing that in a forth-coming patch at eth-gas-reporter and tracking the issue here in #40.
