### ISSUE TITLE
eth-gas-reporter codechecks github actions not showing result or reporting failure (maxMethodDiff)

### ISSUE THREAD

**Issue by wighawag** [cgewecke/hardhat-gas-reporter#43]
I setup hardhat-gas-reporter along with codechecks, including the corresponding github actions in the following repo : 
https://github.com/wighawag/transfer-gateway

I also set: maxMethodDiff = 10

I then pushed a change which caused the gas use to be almost multiplied by 2
But I get nothing from codechecks :

the log shows in both case (before gas increase and after gas increase) : 

```
Run npx codechecks
  npx codechecks
  shell: /bin/bash -e {0}
  env:
    CC_SECRET: ***
CodeChecks Client v.0.1.10
https://codechecks.io

Executing 1 codechecks files

Executing codechecks.yml...

Successful save: output.namespace was: ethGasReporter
Checks: 0 total
Time:   2s
```

Any idea, what I am missing ?

Note that hardhat-gas-reporter itself woks fine, here it its log on CI:

```
Run yarn gas
  yarn gas
  shell: /bin/bash -e {0}
yarn run v1.22.5
$ cross-env REPORT_GAS=true hardhat test
Downloading compiler 0.7.3
Compiling 13 files with 0.7.3
Compilation finished successfully

  ERC20Consumer
    ✓ calling it directly without pre-approval result in Allowance error
    ✓ calling it via erc20transfer gateway works
    ✓ calling it via erc20transfer gateway but with wrong amount fails

·-------------------------------------------------|----------------------------|-------------|----------------------------·
|               Solc version: 0.7.3               ·  Optimizer enabled: false  ·  Runs: 200  ·  Block limit: 9500000 gas  │
··················································|····························|·············|·····························
|  Methods                                                                                                                │
·························|························|··············|·············|·············|··············|··············
|  Contract              ·  Method                ·  Min         ·  Max        ·  Avg        ·  # calls     ·  usd (avg)  │
·························|························|··············|·············|·············|··············|··············
|  ERC20TransferGateway  ·  transferERC20AndCall  ·           -  ·          -  ·     122889  ·           1  ·          -  │
·························|························|··············|·············|·············|··············|··············
|  Deployments                                    ·                                          ·  % of limit  ·             │
··················································|··············|·············|·············|··············|··············
|  DAIWithInitialBalance                          ·           -  ·          -  ·    1265865  ·      13.3 %  ·          -  │
··················································|··············|·············|·············|··············|··············
|  ERC20Consumer                                  ·           -  ·          -  ·     547213  ·       5.8 %  ·          -  │
·-------------------------------------------------|--------------|-------------|-------------|--------------|-------------·

  3 passing (2s)

Done in 7.26s.
```

**Comment by cgewecke** [comment]
Hi @wighawag! 

Codechecks is something that's meant to work with pull requests. And the `diff` is between the results generated for the merge candidate branch and the PRs target. (ex: feat/double-gas vs. master)

A working example that was used to test the `maxMethodDiff`  can be found at https://github.com/cgewecke/gas-check/pull/36

I haven't used CC with GHActions yet - please just lmk if you see problems there. 

(Added myself to the watchlist at `transfer-gateway`)

**Comment by wighawag** [comment]
Hi @cgewecke ok, cool, I understand now. I ll try with a PR and I let you know if I hit any issues with github actions.
Thanks for your work!

**Comment by cgewecke** [comment]
Is this close-able with [transfer-gateway 1][1]?

Have opened an issue at [eth-gas-reporter 230][2] to improve the chart so that the red `X` only shows up on items that trigger the threshold failure.

Atm every increase is marked red, every decrease marked green and it's not instantly clear which gas change caused CI to fail if you're using the threshold option.



[1]: https://github.com/wighawag/transfer-gateway/pull/1
[2]: https://github.com/cgewecke/eth-gas-reporter/issues/230

**Comment by wighawag** [comment]
Yes, this works fine with github actions. 
I agree that having the red X only for item passing the threshold would be better
