### ISSUE TITLE
Not working for internal methods in libraries

### ISSUE THREAD

**Issue by PaulRBerg** [cgewecke/hardhat-gas-reporter#59]
# Description

I have the following set up:

1. Library with pure internal methods
2. Mock contract that exposes the library's internal methods

For which I'm getting no gas report:

<img width="684" alt="No gas report" src="https://user-images.githubusercontent.com/8782666/112354513-6f68e480-8cd5-11eb-8312-6e15e5f2fdc9.png">

I'm not sure if this is caused by my using a library with internal methods or Solidity v0.8 🤔

# Steps to Reproduce

1. git clone git@github.com:paulrberg/prb-math.git
2. cd prb-math
3. git checkout 79def09e62d0f188f55e0abc96c7c7026f370785
4. yarn install
5. REPORT_GAS=true yarn run test

# Environment

+ yarn@1.22.10
+ hardhat@2.1.1
+ hardhat-gas-reporter@1.0.4
+ solidity@0.8.3

**Comment by cgewecke** [comment]
Hmm. Thanks for reporting, will take a look...

**Comment by paulrberg** [comment]
Update: this seems to be about Solidity v0.8, not internal functions in libraries.

I [just](https://github.com/paulrberg/solidity-template/commit/a2508538b2dfcf4106c7b47a7e7cbbd0f91589aa) added hardhat-gas-reporter to my solidity-template, and I am getting no gas report:

<img width="680" alt="Capture d’écran 2021-04-01 à 12 44 09" src="https://user-images.githubusercontent.com/8782666/113275928-f6c2e300-92e7-11eb-9b7c-941deead3a69.png">

**Comment by cgewecke** [comment]
@paulrberg Oh ok! Good to know. I will definitely look at this today....

**Comment by cgewecke** [comment]
@paulrberg The solidity-template has a slightly different problem ...

[This line in the config][1], where `excludeContracts` has an empty string is confusing the reporter's filter logic  
Everything gets skipped because: 
```js
"everything".includes("") === true // ...and profound!
```

The issue with libraries will require a different fix. All the methods you want to measure there are `calls` rather than transactions and the reporter reads gas from tx receipts. 

Will look at adding option to measure these and test against the precision lib this weekend. 

[1]: https://github.com/paulrberg/solidity-template/blob/b70050d4ded3512ca1a484f3d594498c81637b88/hardhat.config.ts#L61

**Comment by paulrberg** [comment]
Re empty string in `excludeContracts` - oh, of course! Thanks for the heads-up. I removed the empty string and it works now.

> The issue with libraries will require a different fix. All the methods you want to measure there are calls rather than transactions and the reporter reads gas from tx receipts.

Interesting. I suppose that in the meantime my best bet is to make the functions in `PRBMathMock` non-constant? Maybe emit an event?

**Comment by bmeredith** [comment]
Would love to include this into my project, but I am also running into this issue unfortunately.

**Comment by cgewecke** [comment]
Support for view and pure methods is added in 2.0 - I think that probably covers this case. The options look like this:
```ts
gasReporter: {
 // This option executes an additional `eth_estimateGas` for every `eth_call`
 // detected by the reporter. If you have 1000's of tests setting it to true has a
 // noticeable performance impact
 reportPureAndViewMethods: true,

 // This option can add several seconds to test startup time if you have
 // 100's of contracts in your project. (It parses all the sources in your dependency tree
 // to identify state variable declarations)
 excludeAutoGeneratedGetters: true,
}
```

Closing for now but please just ping if you feel there's something additional to consider here.

https://github.com/cgewecke/hardhat-gas-reporter/releases/tag/v2.0.0
