### ISSUE TITLE
Feature request: Allow for setting custom eth price 🙏

### ISSUE THREAD

**Issue by DenhamPreen** [cgewecke/hardhat-gas-reporter#65]
Feature request
-----------------------

It would be a nice configuration to be able to set the price of eth when doing gas price calculations. 

This would allow users to view the gas costs for a given eth price. 

A side benefit would allow approx usage when using on EVM layer2's. Ie. Could set the price of 'eth' to the price of Matic when testing on Polygon.

**Comment by cgewecke** [comment]
If a new option called `cryptoCurrency` were added that let you specify the crypto side of the crypto/fiat pair would that work for your use case?

The coinmarketcap API is flexible about this and the gas reporter could make it configurable in [the code here][1]
```js
    const coinmarketcap =
      `https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/` +
      `latest?symbol=ETH&CMC_PRO_API_KEY=${config.coinmarketcap}&convert=`;


    const currencyKey = config.currency.toUpperCase();
    const currencyPath = `${coinmarketcap}${currencyKey}`;
```


The execution costs on Polygon are so low that the gas reporter (w/ 2 decimals of precision for fiat) might not show data for a lot of smaller calls...

If the math below is correct, the worst case cost on Polygon right now (for a whole block at `fastest`) is $0.25  
```
> (7.5 gwei / 1e9) * ($1.70) * 20_000_000
0.25499999999999995
```

A 300k tx at `standard` is $0.00051
```
> (1 / 1e9) * (1.70) * 300_000
0.00051
```

**Resources**

+ Polygon gas prices: `curl https://gasstation-mainnet.matic.network`

[1]: https://github.com/cgewecke/eth-gas-reporter/blob/23fc57687b4e190c7e28571a14773d96cdbf7d63/lib/utils.js#L181

**Comment by cgewecke** [comment]
@DenhamPreen 

Out of curiosity, would adding more decimal places of precision for fiat pricing be useful to you? 

If so, could you describe how you're using this data?

**Comment by DenhamPreen** [comment]
@cgewecke! Thank you for such a detailed response. 

Yes, this would work for our use case. 

Additional decimal places would be useful in this scenario. 

Our use case is a purely `nice to have`, in our https://docs.float.capital we are displaying the approx gas prices to users for different contract calls. 

Less critical with polygon due to the low gas prices making the need or cost to user mostly negligible.

**Comment by DenhamPreen** [comment]
The math on max possible usd cost of a tx on polygon really emphasizes this 😆

**Comment by pasevin** [comment]
Any updates on this, it would be very useful.

**Comment by stevyhacker** [comment]
This would be very useful, I'd like to try to implement it and open a PR for this if this feature is not already in development?

**Comment by tolstenko** [comment]
I am in the same boat. Any updates? @stevyhacker did you make it?

**Comment by cgewecke** [comment]
This is supported in v1.0.5. You can now pick any token to denominate the cost in and configure an endpoint to fetch network specific gas prices for.
