### ISSUE TITLE
Add option to specify price's decimal precision

### ISSUE THREAD

**Issue by Martibis** [cgewecke/hardhat-gas-reporter#88]
I can set currency to ETH, but currently it's limited to 0.01 ETH and I'd like to see it in more detail e.g.: 0.0124885 ETH

**Comment by cgewecke** [comment]
Thanks for this suggestion. Am renaming this issue slightly...

**Comment by Martibis** [comment]
That's definitely a better title (English isn't my first language, so thanks for the improvement)!

**Comment by junhuang-ho** [comment]
Increasing price decimal precision is good for other chains as well like Polygon with very low fees, which currently just displays `0.00`.

**Comment by Biuni** [comment]
Any news?

**Comment by cgewecke** [comment]
This has been added to the latest version (2.0). You can set the currency display's precision as below
```ts
currencyDisplayPrecision: 4. // $0.0007
```

https://github.com/cgewecke/hardhat-gas-reporter/releases/tag/v2.0.0
