### ISSUE TITLE
Working with testnet

### ISSUE THREAD

**Issue by gtsui** [cgewecke/hardhat-gas-reporter#90]
Hi

Is there supposed to be support for this plugin on testnets? For example 

```
npx hardhat test --network rinkeby 
```

seems to freeze the process for me. Is there a solution to this? Thanks.

**Comment by cgewecke** [comment]
@gtsui If you set the option `fast` to true in the gasReporter options, does this unfreeze it?

**Comment by gtsui** [comment]
Yep that seems to work for me now. What does the fast option do?

**Comment by cgewecke** [comment]
Ah it's just a legacy option that was put in when hardhat's async provider support was optional ...

At the moment there is logic here that makes sure users are on the hardhat network but I think it should probably be removed if remote networks work just as well.

https://github.com/cgewecke/hardhat-gas-reporter/blob/e7b2dd642200eca0d4c098c661b39e8d3e6ff4db/src/index.ts#L192-L194

**Comment by cgewecke** [comment]
Closing - this shouldn't be an issue in the latest release (2.0)

https://github.com/cgewecke/hardhat-gas-reporter/releases/tag/v2.0.0
