### ISSUE TITLE
Add option to report view & pure method gas usage

### ISSUE THREAD

**Issue by cgewecke** [cgewecke/hardhat-gas-reporter#92]
We should be able to use `estimateGas` for these. 

It impairs test speeds but this data is important for libraries.

(See [prb-math 70][1])

[1]: https://github.com/paulrberg/prb-math/issues/70

**Comment by cameel** [comment]
For the cases where speed is important you could add a toggle in the config to disable it (I think it should be enabled by default though).

**Comment by cgewecke** [comment]
@cameel Do you think so? 

I am inclined the other way because I've seen estimateGas really slow things down on Hardhat (by more than 2X which is what I would expect) and test suites make so many calls.   

Definitely worth benchmarking on a large project.

**Comment by cameel** [comment]
Ah, that's way more than I expected. If it really slows things down that much then yeah, it might make sense to keep if off by default.

BTW, let me know if you need help benchmarking it on some real-life projects. We have a nice setup in Solidity where we run a bunch of them in CI to test the compiler. As a part of this we can see a breakdown of how long each one took to run the whole test suite: https://app.circleci.com/pipelines/github/ethereum/solidity/22003/workflows/92d7ef3e-f94a-448c-9db1-16cc18d19e9a (all the `t_native_ext_...` and `t_ems_ext_...` jobs are such projects). The time includes compilation, dependency installation, etc. but on the upside it would also show how relevant the slowdown is compared to other factors.

**Comment by cgewecke** [comment]
Oh fantastic, thank you @cameel

**Comment by sebastiantf** [comment]
Would be cool to have this!

**Comment by ItsNickBarry** [comment]
This would be very useful for [SolidState](https://github.com/solidstate-network/solidstate-solidity).

**Comment by cgewecke** [comment]
This has been added in the latest release (2.0). The relevant options look like this
```ts
gasReporter: {
  // This option executes an additional `eth_estimateGas` for every `eth_call`
  // detected by the reporter. If you have 1000's of tests setting it to true has a
  // noticeable performance impact
  reportPureAndViewMethods: true,

  // This option can add several seconds to test startup time if you have
  // 100's of contracts in your project. (It parses all the sources in your dependency tree
  // to identify state variable declarations)
  excludeAutoGeneratedGetters: true,
}
```


https://github.com/cgewecke/hardhat-gas-reporter/releases/tag/v2.0.0
